### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by marziuss** [H4ckd4ddy/flipperzero-sentry-safe-plugin#1]
Hi,
I've a little question about installation. I've downloaded the firmware of official repository, but in the folder tree I don't have the meta folder, and I have both "applications" folder and "applications_user" folder with a readme within that says "Put yout custom application in this folder".
Could you help me with the installation? Where I should to clone your repository and where I have to put the sentry-safe file?
Thanks for your possible support!

**Comment by H4ckd4ddy** [comment]
Hi,
When I created this project, plugins had to be compiled along with the flipper firmware.
Now you can use plugins from sd card.
So the simplest way is to use the [RogueMaster firmware version](https://github.com/RogueMaster/flipperzero-firmware-wPlugins), packaged with a lot of plugins (my Sentry Safe plugin is also included).
But if you want to use the official firmware, I think you can put this [compiled version](https://github.com/H4ckd4ddy/flipperzero-sentry-safe-plugin/files/9608855/sentrysafe.zip) of the plugin on your sd card.
Best regards

**Comment by marziuss** [comment]
> Hi,
> 
> When I created this project, plugins had to be compiled along with the flipper firmware.
> 
> Now you can use plugins from sd card.
> 
> So the simplest way is to use the [RogueMaster firmware version](https://github.com/RogueMaster/flipperzero-firmware-wPlugins), packaged with a lot of plugins (my Sentry Safe plugin is also included).
> 
> But if you want to use the official firmware, I think you can put this [compiled version](https://github.com/H4ckd4ddy/flipperzero-sentry-safe-plugin/files/9608855/sentrysafe.zip) of the plugin on your sd card.
> 
> Best regards
> 
> 

- Yeah, and that's ok. I actually use the official firmware repository but I cannot understand where should I clone your repos because I don't find the "meta" folder in the official repository, I only have "applications" and "applications_user", could you help to tell me the correct steps? Where I have to put the .fam e .c files? Sorry, I'm a beginner :)
Thank you

**Comment by 31337-4554551n** [comment]
So there is no way to compile a plugin without compiling the whole firmware?
Unfortunately when take that compiled file, and try to run it in the official firmware, I get "error. Preload failed. API version mismatch"

**Comment by H4ckd4ddy** [comment]
Hi 👋,
I just push some modifications to fix build issues.
Build instructions also been added.
Best regards
