### ISSUE TITLE
Adopt FuriMutex as API Changes

### ISSUE THREAD

**Issue by debouncedgit** [H4ckd4ddy/flipperzero-sentry-safe-plugin#6]
per https://github.com/csBlueChip/FlipperZero_plugin_howto#the-change-from-valuemutex---furimutex
> In March 2023 the mutex API was "broken"/superceded. Due to changes in the Speaker API (which happened (essentially) at the same time) (and the fact that I didn't really think things through properly) the update to this repository wasn't 'clean'. If you'd like to see a 'clean' update to an app that uses mutex'es, check out [the patch to my WiiEC FAP](https://github.com/csBlueChip/FlipperZero_WiiEC/commit/8ff921b4f8b69fdf60737bdd2b170f0726b719cc)

Currently trying to compile this does not work, at least on current fw versions from what I see.

**Comment by ralphreijs** [comment]
Came here to say this, would be great if anyone could make this compile and work again.

**Comment by bananu7** [comment]
If anyone could test that it'd be great, I don't have an appropriate safe at hand.

**Comment by ralphreijs** [comment]
I will test this weekend to see if I can run the app again. No safe to test at the moment, unfortunately.

**Comment by bananu7** [comment]
For the record, I got it to compile and run on 0.82.3 - I just have no idea if the app still performs correctly.
